---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
  - "css/bootstrap*.*"
  - "js/bootstrap*.*"
